<?php declare(strict_types=1);

namespace Shopware\Core\Checkout\Document\Subscriber;

use Shopware\Core\Checkout\Document\DocumentCollection;
use Shopware\Core\Checkout\Document\DocumentDefinition;
use Shopware\Core\Checkout\Document\Event\DocumentDeletedEvent;
use Shopware\Core\Checkout\Document\Event\DocumentGeneratedEvent;
use Shopware\Core\Defaults;
use Shopware\Core\Framework\Context;
use Shopware\Core\Framework\DataAbstractionLayer\EntityRepository;
use Shopware\Core\Framework\DataAbstractionLayer\EntityWriteResult;
use Shopware\Core\Framework\DataAbstractionLayer\Event\EntityDeleteEvent;
use Shopware\Core\Framework\DataAbstractionLayer\Event\EntityWrittenContainerEvent;
use Shopware\Core\Framework\DataAbstractionLayer\Search\Criteria;
use Shopware\Core\Framework\Log\Package;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Contracts\EventDispatcher\EventDispatcherInterface;

/**
 * Dispatches the after_sales.document.* business events for every producer of document
 * rows (DocumentGenerator, flow action, raw Admin API writes). The document entity is
 * not versioned; its orderVersionId references an order snapshot by design, so only the
 * write context is checked against the live version.
 *
 * @internal
 */
#[Package('after-sales')]
class DocumentBusinessEventSubscriber implements EventSubscriberInterface
{
    /**
     * @param EntityRepository<DocumentCollection> $documentRepository
     *
     * @internal
     */
    public function __construct(
        private readonly EntityRepository $documentRepository,
        private readonly EventDispatcherInterface $eventDispatcher
    ) {
    }

    /**
     * @return array<string, string>
     */
    public static function getSubscribedEvents(): array
    {
        return [
            EntityDeleteEvent::class => 'beforeDelete',
            EntityWrittenContainerEvent::class => 'onEntityWritten',
        ];
    }

    public function beforeDelete(EntityDeleteEvent $event): void
    {
        $context = $event->getContext();
        if ($context->getVersionId() !== Defaults::LIVE_VERSION) {
            return;
        }

        /** @var list<string> $ids */
        $ids = $event->getIds(DocumentDefinition::ENTITY_NAME);
        if ($ids === []) {
            return;
        }

        $documents = $this->documentRepository->search(new Criteria($ids), $context)->getEntities();
        if ($documents->count() === 0) {
            return;
        }

        $event->addSuccess(function () use ($documents, $context): void {
            $deletedAt = (new \DateTimeImmutable())->format(\DATE_ATOM);

            foreach ($documents as $document) {
                $this->eventDispatcher->dispatch(new DocumentDeletedEvent(
                    $context,
                    $document->getId(),
                    $document->getOrderId(),
                    $deletedAt,
                    $document->getDocumentNumber()
                ));
            }
        });
    }

    public function onEntityWritten(EntityWrittenContainerEvent $event): void
    {
        $context = $event->getContext();
        if ($context->getVersionId() !== Defaults::LIVE_VERSION) {
            return;
        }

        $writtenEvent = $event->getEventByEntityName(DocumentDefinition::ENTITY_NAME);
        if ($writtenEvent === null) {
            return;
        }

        foreach ($writtenEvent->getWriteResults() as $writeResult) {
            // Inserts are the only "generated" moment: DocumentGenerator mints a fresh
            // id per generation (media regeneration and uploads are updates by design),
            // and DocumentV2's persister creates rows the same way.
            if ($writeResult->getOperation() !== EntityWriteResult::OPERATION_INSERT) {
                continue;
            }

            $this->dispatchGenerated($writeResult, $context);
        }
    }

    private function dispatchGenerated(EntityWriteResult $writeResult, Context $context): void
    {
        $documentId = $writeResult->getPrimaryKey();
        \assert(\is_string($documentId));

        $payload = $writeResult->getPayload();

        // orderId and documentTypeId are Required fields — a committed insert cannot
        // lack them; their presence is the DAL's invariant, not ours to re-check
        $orderId = $payload['orderId'];
        $documentTypeId = $payload['documentTypeId'];
        \assert(\is_string($orderId) && \is_string($documentTypeId));

        $this->eventDispatcher->dispatch(new DocumentGeneratedEvent(
            $context,
            $documentId,
            $orderId,
            $documentTypeId,
            $this->getDocumentNumber($payload)
        ));
    }

    /**
     * The document_number column is generated by the database from the config JSON
     * (Migration1696300511AddDocumentNumberToDocumentEntity), so it never appears as a
     * top-level key in write payloads — both DocumentGenerator and the DocumentV2
     * persister carry the number inside config.
     *
     * @param array<string, mixed> $payload
     */
    private function getDocumentNumber(array $payload): ?string
    {
        $config = $payload['config'] ?? null;
        if (!\is_array($config)) {
            return null;
        }

        $documentNumber = $config['documentNumber'] ?? null;

        return \is_string($documentNumber) ? $documentNumber : null;
    }
}
